% This is an autogenerated sample test for file all
classdef testall < matlab.unittest.TestCase
    methods (Test)
        function test_all(testCase)
            % Specify the input(s) of all
            sObj = SimulationModel;
            simulate(sObj);

            % Exercise the function all
            output2 = all(ismember(sObj.SimData.DataNames,["Drug","Receptor","Complex","RO"]));


            testCase.verifyClass(sObj.SimData, 'SimData')
            testCase.verifyTrue(output2);
        end
    end
end